// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace BisonHeartGameplayTags
{
	/** Input Tags **/
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxes);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxes);
	
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axes);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axes);

	/** Player Tags **/
	
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axes);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axes);
	
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axes);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axes);
	
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe_Right);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe_Left);

	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axes);
	BISONHEART_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axes);
}
